name: ijon.me
favicon: null
layout_spectrum: 0.36379
typography_spectrum: 0.14878
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2b2b'
    - '#636363'
    - '#101010'
    - '#be1e22'
    - '#d76833'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: 4c178557-e67b-4445-b3de-72825df2f749
    url: null
