name: ijon.me
favicon: null
layout_spectrum: 0.02119
typography_spectrum: 0.52119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2b2b'
    - '#636363'
    - '#101010'
    - '#be1e22'
    - '#d76833'
  brandStrength: 0
  lightness: 0.8
  saturation: 0.5
purpose:
  - name: awareness
    item: null
    url: null
