analytics: {}
color:
  brandColors:
    - '#2B2B2B'
    - '#636363'
    - '#101010'
    - '#BE1E22'
    - '#D76833'
  brandStrength: 0.5625
  lightness: 0.125
  rhythmicContrast: 0.5
  saturation: 0.75
cta: {}
layout_spectrum: 0.388514
name: ijon.me
opengraph: {}
purpose:
  - name: awareness
    item: 'null'
typography_spectrum: 0.14878
