name: ijon.me
favicon: null
layout_spectrum: 0.3
typography_spectrum: 0.7161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#12161f'
    - '#58504d'
    - '#b1adc6'
    - '#cbf55e'
  brandStrength: 0
  lightness: 0.8
  saturation: 0.5
purpose:
  - name: awareness
    item: null
    url: null
